rails g controller booktemplates
rails g controller pagetemplates
rails g controller bookanswers
rails g controller books
rails g controller orders
rails g controller productsubtypes
rails g controller producttypes
rails g controller categories
rails g controller subcategories
rails g controller questions
rails g controller answers
rails g controller imagegalleries
rails g controller images
